/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scan/analysis` | `/scan/analysis`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/goal` | `/goal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scan/camera` | `/scan/camera`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scan` | `/scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stories/food-fact` | `/stories/food-fact`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stories` | `/stories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stories/story-outcome` | `/stories/story-outcome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stories/[storyId]` | `/stories/[storyId]`, params: Router.UnknownInputParams & { storyId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/scan/analysis` | `/scan/analysis`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/goal` | `/goal`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/scan/camera` | `/scan/camera`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/scan` | `/scan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stories/food-fact` | `/stories/food-fact`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stories` | `/stories`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stories/story-outcome` | `/stories/story-outcome`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stories/[storyId]` | `/stories/[storyId]`, params: Router.UnknownOutputParams & { storyId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/scan/analysis${`?${string}` | `#${string}` | ''}` | `/scan/analysis${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/goal${`?${string}` | `#${string}` | ''}` | `/goal${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/scan/camera${`?${string}` | `#${string}` | ''}` | `/scan/camera${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/scan${`?${string}` | `#${string}` | ''}` | `/scan${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stories/food-fact${`?${string}` | `#${string}` | ''}` | `/stories/food-fact${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stories${`?${string}` | `#${string}` | ''}` | `/stories${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stories/story-outcome${`?${string}` | `#${string}` | ''}` | `/stories/story-outcome${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scan/analysis` | `/scan/analysis`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/goal` | `/goal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scan/camera` | `/scan/camera`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scan` | `/scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stories/food-fact` | `/stories/food-fact`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stories` | `/stories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stories/story-outcome` | `/stories/story-outcome`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}/stories/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/stories/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(tabs)'}/stories/[storyId]` | `/stories/[storyId]`, params: Router.UnknownInputParams & { storyId: string | number; } };
    }
  }
}
